version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    hostname: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env.infrastructure
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db.default.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - http
      - db

  pgadmin:
    user: root
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    env_file:
      - .env.infrastructure
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - http

volumes:
  postgres:
  pgadmin-data:

networks:
  http:
    driver: bridge
  db:
    driver: bridge
