version: '3'

services:
  worker:
    image: registry.gitlab.com/muzikanto/backend-starter:latest
    container_name: worker
    hostname: worker
    env_file:
      - .eng.worker
    restart: always
    command: [ 'npm', 'run', 'start:prod:worker']
    ports:
      - '4001:4001'
    networks:
      - http

networks:
  http:
    driver: bridge
