version: '3'

services:
  redis:
    image: redis:6.2-alpine
    command: sh -c "redis-server --save 20 1 --loglevel warning --requirepass $$REDIS_PASSWORD"
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - .env.infrastructure
    volumes:
      - redis:/data


volumes:
  redis:

networks:
  redis:
    driver: bridge
