version: "3.7"

services:
  loki:
    container_name: loki
    image: grafana/loki:2.9.0
    command: "-config.file=/etc/loki/config.yaml -target=all"
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml


networks:
  http:
    driver: bridge
