version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .env.infrastructure
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - rabbitmq:/var/log/rabbitmq

volumes:
  rabbitmq:

networks:
  amqp:
    driver: bridge
