version: '3'

services:
  postgres:
    image: postgres:13
    container_name: shelter_postgres
    hostname: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env.infrastructure.staging
    volumes:
      - ./databases/postgres:/var/lib/postgresql/data
      - ./postgres/db.default.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env.infrastructure.staging
    volumes:
      - ./databases/rabbitmq:/var/lib/rabbitmq
      - ./databases/rabbitmq:/var/log/rabbitmq
    networks:
      - amqp

  redis:
    image: redis:6.2-alpine
    command: sh -c "redis-server --save 20 1 --loglevel warning --requirepass $$REDIS_PASSWORD"
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - .env.infrastructure
    volumes:
      - ./databases/redis:/data

  gateway:
    image: registry.gitlab.com/muzikanto/shelter/server:latest
    container_name: gateway
    hostname: gateway
    restart: always
    depends_on:
      - postgres
      - rabbitmq
      - redis
    command: [ 'npm', 'run', 'start:prod:gateway']
    ports:
      - '4005:4005'
    networks:
      - http
      - db
      - amqp

  migration:
    image: registry.gitlab.com/muzikanto/shelter/server:latest
    container_name: migration
    hostname: migration
    environment:
      NODE_ENV: production
    depends_on:
      - postgres
    command: [ 'node', './dist/apps/gateway/src/migration' ]
    networks:
      - db

  worker:
    image: registry.gitlab.com/muzikanto/shelter/server:latest
    container_name: worker
    hostname: worker
    restart: always
    depends_on:
      - postgres
      - rabbitmq
      - ipfs
    command: [ 'npm', 'run', 'start:prod:worker']
    ports:
      - '4001:4001'
    networks:
      - http
      - db
      - ipfs
      - amqp

volumes:
  postgres:
  rabbitmq:
  redis:
  ipfs:
  elasticsearch:
  prometheus:
  grafana:

networks:
  db:
    driver: bridge
  redis:
    driver: bridge
  amqp:
    driver: bridge
  http:
    driver: bridge
  ipfs:
    driver: bridge
  elk:
    driver: bridge
  analytic:
