{
 "title": "Game",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "users{app=\"CBTW\", type=\"total\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "New Users Last Week",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "users{app=\"CBTW\", type=\"createdLastWeek\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "New Users Last Month",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "users{app=\"CBTW\", type=\"createdLastMonth\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Missions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Win Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "missions{app=\"CBTW\", type=\"winRate\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Missions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "missions{app=\"CBTW\", type=\"total\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Completed Missions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "missions{app=\"CBTW\", type=\"completed\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Finished Missions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "targets": [
      {
       "expr": "missions{type=\"finished\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Loss Missions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "targets": [
      {
       "expr": "missions{app=\"CBTW\", type=\"loos\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Agents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Agents",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "agents{app=\"CBTW\", type=\"total\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Dead Agents",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "agents{app=\"CBTW\", type=\"dead\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total No Salary Agents",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "agents{app=\"CBTW\", type=\"noSalary\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total NFT Agents",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "agents{app=\"CBTW\", type=\"nft\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Agents Count by Levels",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "agents{app=\"CBTW\", type=\"lessThanLevel5\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "agents{app=\"CBTW\", type=\"lessThanLevel10\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "agents{app=\"CBTW\", type=\"lessThanLevel20\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "agents{app=\"CBTW\", type=\"lessThanLevel50\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Bunker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Bunker Laboratories",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "bunker{app=\"CBTW\", type=\"laboratories\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Bunker Cloning",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "targets": [
      {
       "expr": "bunker{app=\"CBTW\", type=\"cloning\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Bunker Equipment",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "targets": [
      {
       "expr": "bunker{app=\"CBTW\", type=\"equipments\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}